name: Build + push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Install Docker and awscli
        run: |
         sudo apt update
         sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
         curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
         sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
         sudo apt update
         sudo apt install docker-ce -y
         sudo apt install awscli -y
         docker --version
         aws --version
      
          
      - name: Retrieve ECR Public authentication token and authenticate Docker client
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l1f8z0w2
          
      - name: Build Docker image
        run : sudo docker build -t pythonimage .
        
      - name: Tag Docker image
        run: |
          docker tag pythonimage:new $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/pythonimage:latest
          
      - name: Push Docker image to ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/pythonimage:new
